name: Build and Start Docker Image

on:
  workflow_dispatch:

jobs:
  update:
    name: Update BeetBox
    runs-on: beetbox

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Bring BeetBox down
        run: docker-compose down

      - name: Build BeetBox
        run: docker build -t beetbox:1.0.0 .
        
      - name: Run BeetBox
        run: docker-compose up
