name: Test

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:
    environment: BeetBox dotenv
    runs-on: self-hosted

    steps:
      - name: Secrets
        run: echo ${{ secrets.BOT_TOKEN }}
      
